### ISSUE TITLE
HLSのお勉強

### ISSUE THREAD

**Issue by DayBySay** [DayBySay/firebase-misc#1]
# TODO:
## must
- [x] HLSの資料集め
- [x] HLSの資料を読む
~- [x] HLSのオンデマンド配信環境をFirebaseにつくる~ （作ったけどAppleの使えばよかった）
- [x] Validationしてみる
- [x] HLS on iOS Appを作って視聴してみる
- [x] HLS配信 on MacOS環境を作ってみる
- [x] HLS配信 on MacOSをiOS Appで視聴してみる

## should
- [x] HLS on HTML5を作って視聴してみる
- [ ] HLS on Androidを作って視聴してみる

# 資料
- [x] [HTTP Live Streaming Overview](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/StreamingMediaGuide/Introduction/Introduction.html)
- [ ] [Working with HTTP Live Streaming](https://developer.apple.com/library/content/documentation/AudioVideo/Conceptual/MediaPlaybackGuide/Contents/Resources/en.lproj/HTTPLiveStreaming/HTTPLiveStreaming.html#//apple_ref/doc/uid/TP40016757-CH11-SW3)
- [x] [HTTP Live Streaming Overview (日本語)](https://developer.apple.com/jp/documentation/NetworkingInternet/Conceptual/StreamingMediaGuide/UsingHTTPLiveStreaming/UsingHTTPLiveStreaming.html)

**Comment by DayBySay** [comment]
資料:
https://developer.apple.com/streaming/

**Comment by DayBySay** [comment]
特徴:
* HTTPで配信できるので、特殊なサーバが不要で通常のWebサーバでいける
  * HTTPSも可
* iOS3以降で使える
* オンデマンドもOK 

ざっくり:
![](https://developer.apple.com/library/content/documentation/NetworkingInternet/Conceptual/StreamingMediaGuide/art/transport_stream_2x.png)
* indexファイル（.m3u8)とメディアセグメントファイル（.ts）の2つのファイルを使う
* クライアントはindexファイルの中身を読んで、取得すべきメディアセグメントファイルを指定し取得する
* indexファイルは都度更新されるため、クライアントはポーリングする必要あり
* iOSの場合、AVFoundatinのAPIを使えば↑の実装がほとんど必要無さそう

**Comment by DayBySay** [comment]
ちなみにAppleが HLS テスト用の環境を用意してくれてる（オンデマンド配信）
https://developer.apple.com/streaming/examples/

**Comment by DayBySay** [comment]
↑のHTML部の実装

```
<div>
<video src="https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_ts/master.m3u8" controls autoplay width="960" height="540"></video>
</div>
```

こんだけ

**Comment by DayBySay** [comment]
通ってる

```
➜  firebase-misc git:(master) ruby validate-hls/validate-hls.rb "https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_ts/master.m3u8"

validate-hls

Validating: Set of 1 URL(s)
| Validating: Playlist(https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_ts/master.m3u8)
| | ✔ Downloadable with 200 OK
| | Validating: Playlist(https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_ts/v5/prog_index.m3u8)
| | | ✔ Downloadable with 200 OK
| | | Validating: Fragment(https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_ts/v5/fileSequence0.ts)
| | | | ✔ Downloadable with 200 OK
| | | | ✔ Keyframe is first frame
| | | Validating: Fragment(https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_ts/v5/fileSequence1.ts)
| | | | ✔ Downloadable with 200 OK
| | | | ✔ Keyframe is first frame
| | | Validating: Fragment(https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_ts/v5/fileSequence2.ts)
...
```

**Comment by DayBySay** [comment]
次はクライアントアプリの勉強。
Apple公式のサンプルを見てみる。

https://developer.apple.com/library/content/samplecode/AVFoundationQueuePlayer-iOS/Introduction/Intro.html

**Comment by DayBySay** [comment]
このサンプルエラー吐いとる・・

```
2018-05-20 11:33:47.131200+0900 AVFoundationQueuePlayer-Swift[57302:822679] Error occurred with message: Optional("Media \"Progressive Download\" failed to load key \"playable\""), error: Optional(Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={NSUnderlyingError=0x604000440150 {Error Domain=NSURLErrorDomain Code=-1200 "An SSL error has occurred and a secure connection to the server cannot be made." UserInfo={NSURLErrorFailingURLPeerTrustErrorKey=<SecTrustRef: 0x60800011c950>, NSLocalizedRecoverySuggestion=Would you like to connect to the server anyway?, _kCFStreamErrorDomainKey=3, _kCFStreamErrorCodeKey=-9802, NSErrorPeerCertificateChainKey=(
    "<cert(0x7f83c705bc00) s: *.test.edgekey.net i: DigiCert SHA2 Secure Server CA>",
    "<cert(0x7f83c705c600) s: DigiCert SHA2 Secure Server CA i: DigiCert Global Root CA>"
), NSUnderlyingError=0x6040004400c0 {Error Domain=kCFErrorDomainCFNetwork Code=-1200 "(null)" UserInfo={_kCFStreamPropertySSLClientCertificateState=0, kCFStreamPropertySSLPeerTrust=<SecTr
```

**Comment by DayBySay** [comment]
動作確認したいだけなので下記対応した

* Info.plist の App Transport Security Settings で Allow Arbitrary Loads -> YESにする
* Info.plist の App Transport Security Settings で Exception Domains 以下を消す

**Comment by DayBySay** [comment]
ちとごちゃついてるけど、この辺で再生するための動画を渡しているっぽい

```
                let newPlayerItem = AVPlayerItem(asset: loadedAsset)
                
                self.player.insert(newPlayerItem, after: nil)
```

**Comment by DayBySay** [comment]
この実装でいけた

```swift
//
//  ViewController.swift
//  Study-HTTPLiveStreaming
//
//  Created by 清 貴幸 on 2018/05/20.
//  Copyright © 2018年 daybysay. All rights reserved.
//

import UIKit
import AVFoundation

class ViewController: UIViewController {
    @IBOutlet weak var playerView: PlayerView!
    
    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        
        let item = AVPlayerItem(url: URL(string: "https://devstreaming-cdn.apple.com/videos/streaming/examples/img_bipbop_adv_example_ts/master.m3u8")!)
        let player = AVPlayer(playerItem: item)
        
        playerView.playerLayer.player = player
        player.play()
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
}

class PlayerView: UIView {
    var player: AVPlayer? {
        get {
            return playerLayer.player
        }
        
        set {
            playerLayer.player = newValue
        }
    }
    
    var playerLayer: AVPlayerLayer {
        return layer as! AVPlayerLayer
    }
    
    override class var layerClass: AnyClass {
        return AVPlayerLayer.self
    }
}

```

**Comment by DayBySay** [comment]
他所様のHLS配信を覗いてみようのコーナー

仕様ツール
* mitm proxy

なるほど

```
2018-05-20 12:10:34 GET https://edge-210-140-227-42.showroom-live.com/liveedge/b6f466163e7540bf9717f233f693ffa2f08968bb7ec23c351405d0981ab22415_low/chunklist_w1070664597.m3u8
                        ← 200 OK application/vnd.apple.mpegurl 177b 46ms
                                    Request                                                                       Response                                                                        Detail
Accept-Ranges:                  bytes
Access-Control-Expose-Headers:  Content-Length
Server:                         WowzaStreamingEngine/4.2.0
Cache-Control:                  no-cache
Access-Control-Allow-Origin:    https://www.showroom-live.com
Access-Control-Allow-Methods:   GET, POST, OPTIONS
Access-Control-Allow-Headers:   Range
Date:                           Sun, 20 May 2018 03:10:37 GMT
Content-Type:                   application/vnd.apple.mpegurl
Content-Length:                 177
Raw                                                                                                                                                                                                                                 [m:auto]
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-ALLOW-CACHE:NO
#EXT-X-TARGETDURATION:3
#EXT-X-MEDIA-SEQUENCE:735
#EXTINF:2.002,
media_w1070664597_735.ts
#EXTINF:2.002,
media_w1070664597_736.ts
```

**Comment by DayBySay** [comment]
2秒に1回くらい？更新しているっぽい

```
2018-05-20 12:10:37 GET https://edge-210-140-227-42.showroom-live.com/liveedge/b6f466163e7540bf9717f233f693ffa2f08968bb7ec23c351405d0981ab22415_low/chunklist_w1070664597.m3u8
                        ← 200 OK application/vnd.apple.mpegurl 177b 90ms
                                    Request                                                                       Response                                                                        Detail
Accept-Ranges:                  bytes
Access-Control-Expose-Headers:  Content-Length
Server:                         WowzaStreamingEngine/4.2.0
Cache-Control:                  no-cache
Access-Control-Allow-Origin:    https://www.showroom-live.com
Access-Control-Allow-Methods:   GET, POST, OPTIONS
Access-Control-Allow-Headers:   Range
Date:                           Sun, 20 May 2018 03:10:39 GMT
Content-Type:                   application/vnd.apple.mpegurl
Content-Length:                 177
Raw                                                                                                                                                                                                                                 [m:auto]
#EXTM3U
#EXT-X-VERSION:3
#EXT-X-ALLOW-CACHE:NO
#EXT-X-TARGETDURATION:3
#EXT-X-MEDIA-SEQUENCE:736
#EXTINF:2.002,
media_w1070664597_736.ts
#EXTINF:2.002,
media_w1070664597_737.ts
```

**Comment by DayBySay** [comment]
これどんなクライアントからも見れてしまうのだろうか？と思って試した所、私の手元のクライアントから見ることができました。

![image](https://user-images.githubusercontent.com/4221188/40275325-89f8ac36-5c27-11e8-90aa-4574a74aa852.png)

実装

```
        let item = AVPlayerItem(url: URL(string: "https://edge-210-140-227-42.showroom-live.com/liveedge/b6f466163e7540bf9717f233f693ffa2f08968bb7ec23c351405d0981ab22415_low/playlist.m3u8")!)
```

**Comment by DayBySay** [comment]
これ、VRChatにHLS対応のスクリーンを作れば、東雲めぐちゃんの配信をVRChat内で見られる可能性

**Comment by DayBySay** [comment]
視聴側の雰囲気はわかってきたので、次は配信

**Comment by DayBySay** [comment]
FFMpegでできそう

https://trac.ffmpeg.org/wiki/Capture/Webcam

**Comment by DayBySay** [comment]
見ている
https://stackoverflow.com/questions/37960828/webcam-streaming-from-mac-using-ffmpeg
http://ffmpeg.org/ffmpeg.html#Synopsis

**Comment by DayBySay** [comment]
ffmpegでwebcamのビデオをエンコードでしてmediastreamsegmenterに渡せるかなーというのを試している

**Comment by DayBySay** [comment]
それっっぽい
https://stackoverflow.com/questions/16469704/mediastreamsegmenter-stops-sending-id3-metadata-using-hls

**Comment by DayBySay** [comment]
https://www.ffmpeg.org/ffmpeg-formats.html

**Comment by DayBySay** [comment]
ローカルでサーバをたてて、MacのCameraから取得した映像をHLS形式で配信してiOS Simulatorで見ている所
![image](https://user-images.githubusercontent.com/4221188/40288647-293ad07c-5cef-11e8-897c-630cee2a5de9.png)

**Comment by DayBySay** [comment]
Macのサファリからみているところ
![image](https://user-images.githubusercontent.com/4221188/40288746-a14c99ce-5cef-11e8-901d-3cf5a738f44c.png)
